### ISSUE TITLE
Code for hierarchical class clustering 

### ISSUE THREAD

**Issue by Tianqi-py** [cdjkim/PRS#20]
Hi,

thanks for making the code publicly accessible. I was wondering if the code for creating the sequential multi-label datasets using the hierarchical class clustering algorithm is also published somewhere?

Thanks for your help!

**Comment by cdjkim** [comment]
Hi Tianqi,

Firstly, apologies for the late response. 
As the data ids for both COCOseq and NUS-WIDEseq are released in the split state for benchmarking purposes, we did not release the code for creating the sequential multi-label datasets. 

In the supplementary's Section 8.2 and Algorithm 2, we believe sufficient details were given about this topic (using sklearn's clustering algorithms should make your life even simpler). 

Sincerely,
Chris.
