### ISSUE TITLE
Possible duplicates between validation and training data in NUS-WIDE splits

### ISSUE THREAD

**Issue by tdemin16** [cdjkim/PRS#21]
Dear authors, I was looking at the json file ids under the NUSWIDESeq directory and noticed some duplicates between the training and validation sets.
More specifically, by creating two sets that collect validation and training ids, and computing their intersection, I noticed 717 (~30.3%) images shared between the training and validation sets.
I checked some of the ids I found with my code directly in this repo, and the problem seems to be there too.
This is the code I used (in the outputs I printed ten duplicates):
```python
import json
import os


def check_duplicates(data):
    val_data = [img for key, val in data.items() for img in val if 'val' in key]
    train_data = [img for key, val in data.items() for img in val if 'train' in key]

    stats = {
        "val": len(val_data),
        "val_set": len(set(val_data)),
        "train": len(train_data),
        "train_set": len(set(train_data)),
        "intersection": len(set(val_data).intersection(set(train_data))),
        "first_ten": list(set(val_data).intersection(set(train_data)))[:10],
    }

    return stats


def main():
    root = 'couple/continual_datasets/'
    
    # I collected all data inside two json files to be easier to handle.
    filenames = ['nus_wide_data.json', 'coco_data.json']

    for filename in filenames:
        with open(os.path.join(root, filename), 'r') as f:
            data = json.load(f)
        
        stats = check_duplicates(data)
        print(filename, stats)


if __name__ == "__main__":
    main()
```
```
Output
>>> nus_wide_data.json {'val': 2366, 'val_set': 2366, 'train': 48748, 'train_set': 48748, 'intersection': 717, 'first_ten': [0, 1, 40960, 3, 4, 40963, 65542, 43009, 73729, 32777]}
>>> coco_data.json {'val': 6366, 'val_set': 6366, 'train': 35072, 'train_set': 35072, 'intersection': 0, 'first_ten': []}
```

Are these jsons used to split the data between training and validation? In that case, shouldn't they contain different data?

**Comment by cdjkim** [comment]
Hi, Thomas

In response to your inquiry, they do contain different data! The train JSON corresponds to the line indices contained within the `TrainImageList.txt` file, which are derived from the original NUS-WIDE dataset. Likewise, the test JSON aligns with the line indices that are located within the `TestImageList.txt` file, also from the original NUS-WIDE dataset.

Kind regards,
Authors
