### ISSUE TITLE
Computation requirement

### ISSUE THREAD

**Issue by muliyangm** [cdjkim/PRS#6]
Thank you for sharing the excellent work!

I'd like to ask what is the typical training time as well as the CUDA memory requirement for the two datasets?

**Comment by cdjkim** [comment]
Hi Muli,

On Quadro RTX, the training time on our reported results on COCOseq and NUS-WIDEseq takes roughly 2 and 2.5 hours respectively. The required memory with a slight buffer between task shifts ranges between 6.5Gb~7Gb for both datasets.

Chris

**Comment by muliyangm** [comment]
Thanks for your kind reply!

**Comment by valencebond** [comment]
> Thanks for your kind reply!

can you success reimplement the performance reported by the paper?

**Comment by muliyangm** [comment]
> > Thanks for your kind reply!
> 
> can you success reimplement the performance reported by the paper?

I had not tried this code. Sorry for that.

**Comment by cdjkim** [comment]
Hi, regarding the performance reproducibility follow [here](https://github.com/cdjkim/PRS/issues/15)!
